# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  echo:
    name: "Test workflow"
    runs: echo "${{matrix.os}}
